### ISSUE TITLE
QRcode generation

### ISSUE THREAD

**Issue by pranjalisnow** [manifestinteractive/teleprompter#30]
This is not actually an issue.

Wanted help on setting up for generating QRcode on a LAN-based website
Currently, the QRcode is generated using this URL: https://promptr.tv/remote/socket.io/socket.io.js
Tried downloading this JS and using, but didn't work.

Request for the steps to enable generating QRcode locally without internet access.

Regards.

**Comment by LaughterOnWater** [comment]
This package is tied in several of the documents to promptr.tv. Like you, I would rather serve the code locally. While it may technically be secure, it's my data in someone else's hands for reasons I don't know about. Cursorily, it looks like plugins.js has several functions, one of which probably has hidden the variable for the promptr.tv remote link used to create the canvas QR Code. From the point of view of a neophyte, it looks like Peter is hiding something for unknown reasons. Perhaps he'll explain   why we can't simply host this locally for logical reasons. Peter?

**Comment by manifestinteractive** [comment]
@pranjalisnow The reason this did not work is because you cannot just download a socket.  This needs to be run on a node server ( and not just that one file, you need to run the app that hosts that socket instance ).

Most of the users of this software were simply using the website to load up a teleprompter, and even running it locally, this feature would still work if you had internet access ( which is required for the remote to work anyway ).  I personally did not think users of this software would want to go through the efforts of spinning up an additional node server just to act as a remote control service in addition to running the main software on a device.

This is 100% the reason that code was not part of this project, because it did not seem like it needed to be.  However, I can certainly make a new repo that is just for the remote portion of this software.

@LaughterOnWater yes, stuff is being hidden on the client side, but that is absolutely to protect the different sessions that might be using the remote.  This exact same remote server works for EVERYONE, but needs to have some privacy to only allow people connecting from one session to connect to THEIR session remotely.  Otherwise you could try to reverse engineer how the remote system works and try to connect to other remote instances to control them.

In all honesty, this the the main reason I did not release the software.  In addition to it not really being something most users needed to be running on their own, exposing the code could allow others to reverse engineer the code to see how the remote works, and in theory, would be something an attacker could exploit.

But hey, this is free software right? You want to have that code?  Sure thing.  I will make a new repo, and if anyone asks why I released the code, I can point here :)

**Comment by manifestinteractive** [comment]
@pranjalisnow The reason this did not work is because you cannot just download a socket. This needs to be run on a node server ( and not just that one file, you need to run the app that hosts that socket instance ).

All of the code you need to run this is already in the repo. You simply need to run the server.js file on a server using node.

You'll obviously also need to change all the https://promptr.tv/remote/socket.io/socket.io.js URL's to wherever you are running this server.

To be 100% clear, this repo and all of its code is for what is running on https://promptr.tv

You can certainly clone / fork this repo and use as you wish.  There is nothing "hidden" in this code.  If you are familiar with NPM, you can simply do the following to get your own version of the code running locally:

```bash
git clone https://github.com/manifestinteractive/teleprompter.git
cd teleprompter
npm install
npm start
```

But you will need to replace all instances of `https://promptr.tv` with your own server.

**Comment by manifestinteractive** [comment]
If it's helpful, this is the Nginx Config I use for my actual server.  You will notice I made a custom route for `/remote` what is a proxy for port `3000`.  So if you just want to use the port as is, you will want to change `https://promptr.tv/remote/socket.io/socket.io.js` in the source code to wherever that actual server is running, e.g. `http://localhost:3000/socket.io/socket.io.js`

```
server {
  listen 80;
  listen [::]:80;
  server_name promptr.tv www.promptr.tv;
  return 301 https://$server_name$request_uri;
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  include snippets/ssl-promptr.tv.conf;
  include snippets/ssl-params.conf;
  include snippets/basic.conf;
  include snippets/error-pages.conf;

  add_header X-Frame-Options DENY;

  root /var/www/promptr.tv/html;
  index index.php index.html index.htm index.nginx-debian.html;

  server_name promptr.tv www.promptr.tv;

  location / {
    try_files $uri $uri/ =404;
  }

  location ^~ /remote/ {
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_http_version 1.1;
    proxy_pass http://localhost:3000/;
  }
}
```

**Comment by LaughterOnWater** [comment]
These are all fantastic answers! This is a lovely piece of craftsmanship. I greatly appreciate your consideration for making it secure for each instance, and now understand that as a proof of concept it's the safest way to go! I'll see if I can set up a server on node and try it out! Thank you so much for making all of this clear.

**Comment by pranjalisnow** [comment]
Thank you, Peter.
