### ISSUE TITLE
tricky keyboard

### ISSUE THREAD

**Issue by snchzantonio** [manifestinteractive/teleprompter#6]
sometimes when i click in the contenteditable area and press f12 to debug the console dont show, same hapens when click on the options bar

**Comment by manifestinteractive** [comment]
Need to know what browser and operating system you are using.  Normally though in editable fields, some keyboard shortcuts will not work the same as you are in a data entry field at that point.  Most function keys should act the same regardless, but I just wanted to note that it is technically possible that your computer just handles function keys differently when you are in an input field rather than just anywhere else.

Knowing you browser and operating system will help clear that up.

**Comment by snchzantonio** [comment]
ok, so:

windows 10 pro 64bit
chrome 55
keyboard layout: ESP-ES (Spanish, Venezuela)

**Comment by manifestinteractive** [comment]
This is not technically a bug.  You are editing a document, so keyboard presses inside this document will not work the same as if you were in a normal website.  You will need to click out of the editable area to use normal keyboard function.  In v1.2.0 we are adding support for the <kbd>ESC</kbd> key to exit out of editing mode ( this was a feature request ).
