### ISSUE TITLE
Where are the source files for style.*.css and plugins.*.js?

### ISSUE THREAD

**Issue by rkaiser0324** [manifestinteractive/teleprompter#62]
### Question

It looks like style.*.css is compiled from LESS or similar, and plugins.*.js is minified.  If so, can you include those source files and toolchain instructions for compilation to CSS and JS (i.e., do you use Grunt etc.)? Then we can contribute PRs that affect these assets.

**Comment by manifestinteractive** [comment]
Nope, they're not.  This is just me being lazy.  Original code was just regular HTML / CSS / JS without any build tools.  That resulted in a need to break cache when deployed, so just renaming the files is all that was needed, so just used the version number as a cache busting mechanism.

Honestly probably makes sense to automate all that with maybe gulp and sass, but ya, it's been a manual process since it only took like two seconds to change the file name vs the time it would take to refactor this to require more complex build tools.

Closing this issue though since the answer to the question is "those are the source files" but I'd welcome a PR that did this if anyone had free time ;)
